
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.mvc.throw-exception-if-no-handler-found=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.path=/v3/api-docs0
springdoc.swagger-ui.path=/swagger-ui.html
server.port=9090

jwt.secret=sE5Fzn9qk0w5EiLw1XOgUfcwBHt6DdIX2V2ein/KuKA=ksd5465s/Gss5GS2DFHCWDNI]\52PSE7752Q
jwt.expiration=86400000

# TMDB API URL's
tmdb.api-key=73caea9b506ae234c9641d204af978c5
tmdb.popular-movies-url = https://api.themoviedb.org/3/movie/popular?api_key=
tmdb.genre-url = https://api.themoviedb.org/3/genre/movie/list?api_key=73caea9b506ae234c9641d204af978c5&language=en-US
tmdb.credits-url = https://api.themoviedb.org/3/movie/{movieId}/credits?api_key=${tmdb.api-key}

# OpenRouter API Key
openrouter.api-key=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
openrouter.base-url=https://openrouter.ai/api/v1

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true