spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.mvc.thow-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
server.port=9090

jwt.secret=sE5Fzn9qk0w5EiLw1XOgUfcwBHt6DdIX2V2ein/KuKA=ksd5465s/Gss5GS2DFHCWDNI]\52PSE7752Q
jwt.expiration=86400000

tmbd.api-key=4aeee56ccb609a8f4791aa0033a54147
tmdb.movie-url = https://api.themoviedb.org/3/movie/popular?api_key=
tmbd.genre-url = https://api.themoviedb.org/3/genre/movie/list?api_key=4aeee56ccb609a8f4791aa0033a54147&language=en-US

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true