spring.application.name=Movie-Recommendation-API
spring.datasource.url=jdbc:postgres://localhost:5432/moviesdb
spring.datasource.username=user
spring.datasource.password=pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
